name: responsible_kid

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  internet_connection_checker: ^1.0.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  lottie: ^3.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/jsons/
  fonts:
    - family: Times
      fonts:
        - asset: assets/fonts/timesFont.ttf
    - family: Elora
      fonts:
        - asset: assets/fonts/eloraFont.otf
    - family: Jacques
      fonts:
        - asset: assets/fonts/jacquesFont.ttf