// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF_jsIi2Si5dXEKvXhKPrjZYxm7JoZqyU',
    appId: '1:1042069687364:web:22b01e28ad8c6b7bcd8011',
    messagingSenderId: '1042069687364',
    projectId: 'responsible-kid',
    authDomain: 'responsible-kid.firebaseapp.com',
    storageBucket: 'responsible-kid.appspot.com',
    measurementId: 'G-7B117GFP2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr_ZEu5TiEvL3QEWTUP6RvrtBGiAYGvWc',
    appId: '1:1042069687364:android:9efd7869d84cf50ecd8011',
    messagingSenderId: '1042069687364',
    projectId: 'responsible-kid',
    storageBucket: 'responsible-kid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhCPyQdVTwxLwn64WaA0bk2Ig6GpXxVLU',
    appId: '1:1042069687364:ios:a1fd634b946d6ce5cd8011',
    messagingSenderId: '1042069687364',
    projectId: 'responsible-kid',
    storageBucket: 'responsible-kid.appspot.com',
    iosBundleId: 'com.example.responsibleKid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhCPyQdVTwxLwn64WaA0bk2Ig6GpXxVLU',
    appId: '1:1042069687364:ios:3439f515f5aba8a7cd8011',
    messagingSenderId: '1042069687364',
    projectId: 'responsible-kid',
    storageBucket: 'responsible-kid.appspot.com',
    iosBundleId: 'com.example.responsibleKid.RunnerTests',
  );
}
